export default {
  singleQuote: true,
  semi: true,
  tabWidth: 2,
  useTabs: false,
  trailingComma: 'es5',
  bracketSameLine: false,
  vueIndentScriptAndStyle: true,
  printWidth: 80,
  plugins: [
    'prettier-plugin-vue',
    'prettier-plugin-organize-imports',
    'prettier-plugin-organize-attributes',
  ],
  attributeGroups: [
    '^((v-bind)?:?|v-)is$',
    '^v-for$',
    '^v-(if|else-if|else|show|cloak)$',
    '^v-(once|pre|memo)$',
    '^(v-bind)?:?id$',
    '^(v-bind)?:?key$',
    '^(v-bind)?:?ref$',
    '^(v-)?slot$',
    '^#',
    '^v-model$',
    '^v-(?!bind(:|$)|on(:|$)|html$|text$)',
    '^class$',
    '^(v-bind)?:class$',
    '^((v-bind)?:)?(?!data-|v-|:|@|#)',
    '$DEFAULT',
    '^((v-bind)?:)?data-',
    '^v-bind$',
    '^v-on:',
    '^@',
    '^v-html$',
    '^v-text$',
  ],
  singleAttributePerLine: true,
  htmlWhitespaceSensitivity: 'ignore',
};
